# Generated by Django 2.0.13 on 2019-03-04 08:04

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('allow_retries', 'allow_retries'), ('answers', 'answers'), ('answers_selected', 'answers_selected'), ('assessable', 'allow_retries'), ('caption_custom_text', 'caption_custom_text'), ('caption_field', 'caption_field'), ('coupon_amount', 'coupon_amount'), ('course_setting', 'course_setting'), ('course_start_date', 'course_start_date'), ('cp_allow_discussion', 'cp_allow_discussion'), ('cp_allow_grades', 'cp_allow_grades'), ('cp_allow_workbook', 'cp_allow_workbook'), ('cp_basic_certificate', 'cp_basic_certificate'), ('cp_basic_certificate_layout', 'cp_basic_certificate_layout'), ('cp_certificate_background', 'cp_certificate_background'), ('cp_certificate_logo', 'cp_certificate_background'), ('cp_cert_margin', 'cp_cert_margin'), ('cp_cert_text_color', 'cp_cert_text_color'), ('cp_class_limited', 'cp_class_limited'), ('cp_class_size', 'cp_class_size'), ('cp_course_completion_content', 'cp_course_completion_content'), ('cp_course_completion_title', 'cp_course_completion_title'), ('cp_course_end_date', 'cp_course_end_date'), ('cp_course_failed_content', 'cp_course_failed_content'), ('cp_course_failed_title', 'cp_course_failed_title'), ('cp_course_language', 'cp_course_language'), ('cp_course_open_ended', 'cp_course_open_ended'), ('cp_course_start_date', 'cp_course_start_date'), ('cp_course_view', 'cp_course_view'), ('cp_enrollment_end_date', 'cp_enrollment_end_date')], max_length=100, verbose_name='Name')),
                ('value', models.TextField(verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('order_type', models.CharField(choices=[('PP', 'Pending payment'), ('PR', 'Processing'), ('OH', 'On hold'), ('CP', 'Completed'), ('CL', 'Cancelled'), ('RF', 'Refaunded'), ('FA', 'Failed')], default='PP', max_length=2, verbose_name='Order type')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('order_actions', models.CharField(blank=True, choices=[('EI', 'Email invoice / order details to customer'), ('RN', 'Resend new order notification'), ('GN', 'Regenerate download permissions')], default='EI', max_length=2, null=True, verbose_name='Order actions')),
                ('downloadable_product_permission', models.CharField(blank=True, max_length=255, null=True, verbose_name='Downloadable product permissions')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First_name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last_name')),
                ('company', models.CharField(blank=True, max_length=20, null=True, verbose_name='Company')),
                ('address_line_one', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 1')),
                ('address_line_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('post_code', models.PositiveIntegerField(blank=True, max_length=10, null=True, verbose_name='Post code / ZIP')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Country')),
                ('state_or_country', models.CharField(blank=True, max_length=20, null=True, verbose_name='State / Country')),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('payment_method', models.CharField(choices=[('NA', 'N/A'), ('CA', 'Check booking availability'), ('OT', 'Other')], default='NA', max_length=2, verbose_name='Payment method')),
                ('transaction_id', models.PositiveIntegerField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('PN', 'Private note'), ('NC', 'Note to customer')], default='PN', max_length=2, verbose_name='Note type')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_note', to='wc_orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First_name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last_name')),
                ('company', models.CharField(blank=True, max_length=20, null=True, verbose_name='Company')),
                ('address_line_one', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 1')),
                ('address_line_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('post_code', models.PositiveIntegerField(blank=True, max_length=10, null=True, verbose_name='Post code / ZIP')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Country')),
                ('state_or_country', models.CharField(blank=True, max_length=20, null=True, verbose_name='State / Country')),
                ('customer_provided_note', models.TextField(blank=True, null=True, verbose_name='Customer provided note')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='billing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wc_orders.OrderBilling'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wc_orders.OrderShipping'),
        ),
        migrations.AddField(
            model_name='customfields',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_custom_field', to='wc_orders.Order'),
        ),
    ]
