# Generated by Django 2.0.13 on 2019-03-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_orders', '0002_ordernote_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbilling',
            name='post_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Post code / ZIP'),
        ),
        migrations.AlterField(
            model_name='orderbilling',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordershipping',
            name='post_code',
            field=models.PositiveIntegerField(null=True, verbose_name='Post code / ZIP'),
        ),
    ]
