# Generated by Django 2.0.13 on 2019-03-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_orders', '0003_auto_20190304_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Order number'),
        ),
    ]
