# Generated by Django 2.0.13 on 2019-03-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_orders', '0004_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernote',
            name='date_created',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date created'),
        ),
    ]
