# Generated by Django 2.0.13 on 2019-03-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_orders', '0005_ordernote_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_actions',
            field=models.CharField(blank=True, choices=[('Email invoice / order details to customer', 'Email invoice / order details to customer'), ('Resend new order notification', 'Resend new order notification'), ('Regenerate download permissions', 'Regenerate download permissions')], default='Email invoice / order details to customer', max_length=100, null=True, verbose_name='Order actions'),
        ),
    ]
