# Generated by Django 2.0.11 on 2019-02-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20190211_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='account_name',
            new_name='contact_name',
        ),
    ]
