# Generated by Django 2.0.11 on 2019-02-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20190212_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='contact_name',
            new_name='contact_email',
        ),
    ]
