# Generated by Django 2.0.13 on 2019-03-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wc_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.PositiveIntegerField(max_length=50, unique=True, verbose_name='Coupon code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('PD', 'Percentage discount'), ('FC', 'Fixed card discount'), ('FP', 'Fixed product discount'), ('BP', 'Booking person discount')], default='PD', max_length=2, verbose_name='Discount type')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Allow free shipping')),
                ('expiry_date', models.DateField(db_index=True, verbose_name='Coupon expiry date')),
                ('minimum_spend', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum spend')),
                ('maximum_spend', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum spend')),
                ('individual_use_only', models.BooleanField(default=False, verbose_name='Individual use only')),
                ('exclude_sale_items', models.BooleanField(default=False, verbose_name='Exlude sale items')),
                ('usage_limit_per_coupon', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage limit per coupon')),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage limit per user')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='wc_orders.Order')),
            ],
        ),
    ]
