# Generated by Django 2.0.13 on 2019-03-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.PositiveIntegerField(unique=True, verbose_name='Coupon code'),
        ),
    ]
